AllCops:
  Exclude:
    - config/unicorn.rb
    - db/**/*
    - vendor/**/*
    - bin/**
    - lib/tasks/sample.rake
    - lib/jellyfish_fog_aws/spec/dummy/**/*
  RunRailsCops: true

ClassLength:
  Max: 300

MethodLength:
  Max: 50

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 38

Style/GlobalVars:
  AllowedVariables: [$evm]

Rails/HasAndBelongsToMany:
  Enabled: false

GuardClause:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClosingParenthesisIndentation:
  Enabled: false
