---
version: '2'
services:
  app:
    ports:
    - 3000:3000
    command: bundle exec puma -C config/puma.rb
    extends:
      service: common
    links:
    - db
  worker:
    extends:
      service: common
    links:
    - redis
    - db
    depends_on:
    - redis
    - db
    command: bundle exec rake jobs:work
  common:
    build: "."
    environment:
      NODE_ENV: production
      RACK_ENV: production
      DATABASE_URL: postgres://postgres:688OMWXwaaD-nw1Yf8R6fg@db:5432/postgres
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 688OMWXwaaD-nw1Yf8R6fg
